GET http://localhost:3001/tasks

###

POST http://localhost:3001/tasks/new
Content-Type: application/json

{
  "description": "Task 2 description"
}

###

DELETE http://localhost:3001/tasks/delete/623e92b4dabbfe8d5e235bc5

###

PUT http://localhost:3001/tasks/complete/623e952178db968a51200e24