GET http://localhost:3001/tasks

###

POST http://localhost:3001/tasks/new
Content-Type: application/json

{
  "description": "Task 3 description"
}

###

DELETE http://localhost:3001/tasks/delete/623e93a23fb42c9903c4512d

###

PUT http://localhost:3001/tasks/complete/623e952178db968a51200e24